export const areaOptions = [
    { value: "Nikol", label: "Nikol" },
    { value: "Naroda", label: "Naroda" },
    { value: "Shivranjani", label: "Shivranjani" },
    { value: "Naranpura", label: "Naranpura" },
    { value: "Vastral", label: "Vastral" },
    { value: "Viratnagar", label: "Viratnagar" },
    { value: "Hanspura", label: "Hanspura" },
    { value: "Hathijan", label: "Hathijan" },
    { value: "Dehgam", label: "Dehgam" },
    { value: "Chandkheda", label: "Chandkheda" },
    { value: "Ranip", label: "Ranip" },
    { value: "Maninagar", label: "Maninagar" },
    { value: "Juhapura", label: "Juhapura" },
    { value: "Iskon", label: "Iskon" },
    { value: "Bopal", label: "Bopal" },
    { value: "South Bopal", label: "South Bopal" },
    { value: "Sindhubhavan", label: "Sindhubhavan" },
    { value: "Vadaj", label: "Vadaj" },
    { value: "Ognaj", label: "Ognaj" },
    { value: "Ghatlodia", label: "Ghatlodia" },
    { value: "Prahladnagar", label: "Prahladnagar" },
    { value: "Vaisnodevi", label: "Vaisnodevi" },
    { value: "Gota", label: "Gota" },
    { value: "Krishnanagar", label: "Krishnanagar" },
    { value: "Memco", label: "Memco" },
    { value: "Bapunagar", label: "Bapunagar" },
    { value: "New Naroda", label: "New Naroda" },
    { value: "Sartej", label: "Sartej" },
    { value: "Science City", label: "Science City" },
    { value: "Ctm", label: "Ctm" },
    { value: "Ghodasar", label: "Ghodasar" },
    { value: "Narol", label: "Narol" },
    { value: "Kalupur", label: "Kalupur" },
    { value: "Lal Darvaja", label: "Lal Darvaja" },
    { value: "Saraspur", label: "Saraspur" },
    { value: "Vastrapur", label: "Vastrapur" },
    { value: "Memnagar", label: "Memnagar" },
    { value: "Delhi Darvaja", label: "Delhi Darvaja" },
    { value: "Sahibaug", label: "Sahibaug" },
];

export const colleageOptions = [
    { value: "Monark university", label: "Monark university" },
    { value: "L j college", label: "L j college" },
    { value: "Silver oak university", label: "Silver oak university" },
    { value: "Karnavati university", label: "Karnavati university" },
    { value: "Gujarat college", label: "Gujarat college" },
    { value: "Gujarat university", label: "Gujarat university" },
    { value: "Jg college", label: "Jg college" },
    { value: "Gov polytechnic", label: "Gov polytechnic" },
    { value: "Somlalit college", label: "Somlalit college" },
    { value: "Pdpu", label: "Pdpu" },
    { value: "Swami Vivekanand college", label: "Swami Vivekanand college" },
    { value: "Seth cn college", label: "Seth cn college" },
    { value: "Cept university", label: "Cept university" },
    { value: "Parul university", label: "Parul university" },
    { value: "Nirma university", label: "Nirma university" },
    { value: "Anant national university", label: "Anant national university" },
    { value: "St xaviers college", label: "St xaviers college" },
    { value: "H l commerce college", label: "H l commerce college" },
    { value: "Bhavans college", label: "Bhavans college" },
    { value: "Amor design institure", label: "Amor design institure" },
    { value: "Bhanwar rathod design studio", label: "Bhanwar rathod design studio" },
    { value: "Nifd design", label: "Nifd design" },
    { value: "Alfa college", label: "Alfa college" },
    { value: "Gov commerce college", label: "Gov commerce college" },
    { value: "C u shah college", label: "C u shah college" },
    { value: "H a college", label: "H a college" },
    { value: "Lokmanya college", label: "Lokmanya college" },
    { value: "Viswakarma gov eng college", label: "Viswakarma gov eng college" },
    { value: "Gls university", label: "Gls university" },
    { value: "Indus university", label: "Indus university" },
    { value: "Indrashil university", label: "Indrashil university" },
    { value: "B j medical college", label: "B j medical college" },
    { value: "Sal university", label: "Sal university" },
    { value: "L m pharmacy college", label: "L m pharmacy college" },
    { value: "Adani institute", label: "Adani institute" },
    { value: "Swarnim university", label: "Swarnim university" },
    { value: "Swaminarayan college", label: "Swaminarayan college" },
    { value: "Nhl medical college", label: "Nhl medical college" },
];

export const ageOptions = Array.from({ length: 13 }, (_, i) => ({
    value: (18 + i).toString(),
    label: (18 + i).toString(),
}));

export const genderOptions = [
    { value: "male", label: "Male" },
    { value: "female", label: "Female" },
    { value: "prefer-not-to-say", label: "Prefer not to say" },
];